<a href="https://colab.research.google.com/github/mgultekin/NLPinTensorflow/blob/main/NlpTrainingW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###NLP in Tensorflow Course Week 1

In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
             'I love my dog',
             'I love my cat'
             ]

tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)


{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
sentences = [
             'I really love my dog',
             'My dog loves my manatee'
             ]
test_seq = tokenizer.texts_to_sequences(sentences)
print(test_seq)

#if we dont have familiar word(unseen) like 'really'  

[[1, 2, 3, 4], [3, 4, 3]]


In [2]:
#now lets use some different attributes
#run this code with its own

import tensorflow as tf
from tensorflow import keras 

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

tokenizer = Tokenizer(num_words = 100, oov_token= '<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen = 10)
print('\nWord Index = ', word_index)
print('\nSequences = ', sequences)
print("\nPadded Sequences:")
print(padded)


# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq, maxlen = 10)
print("\nPadded Test Sequence: ")
print(padded)










Word Index =  {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}

Sequences =  [[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]

Padded Sequences:
[[ 0  0  0  0  0  0  5  3  2  4]
 [ 0  0  0  0  0  0  5  3  2  7]
 [ 0  0  0  0  0  0  6  3  2  4]
 [ 0  0  0  8  6  9  2  4 10 11]]

Test Sequence =  [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

Padded Test Sequence: 
[[0 0 0 0 0 5 1 3 2 4]
 [0 0 0 0 0 2 4 1 2 1]]


In [ ]:
###Week2###

In [1]:
import tensorflow as tf
print(tf.__version__)



2.4.1


In [5]:
!pip install -q tensorflow-datasets

In [6]:
import  tensorflow_datasets as tfds

In [ ]:
imdb, info = tfds.load('imdb_reviews', with_info = True, as_supervised = True)